name: Allowed-branch-merge

on:
  pull_request_target:
     branches:
        - main
#       - feature-*-*
#       - release-*-*

jobs:
  allowed-merge:
    if: ${{ github.head.ref == 'feature-*' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo-Success
        run: |
          echo "This is an allowed branch being merged"
  
  blocked-merge:
    if: ${{ github.head.ref == 'feature-*' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo-failure
        run: |
          echo "This is not an allowed branch $GITHUB_HEAD_REF"
          exit 1
