name: Allowed-branch-merge

on:
  pull_request_target:
     branches:
        - main
#       - feature-*-*
#       - release-*-*

# Is this a good way of should I use webhooks instead to capture PR creation and close it out instead.

jobs:
  allowed-merge:
    if: ${{ startsWith( github.head.ref , 'feature-' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo-Success
        run: |
          echo "This is an allowed branch being merged"
  
  blocked-merge:
    if: ${{ !startsWith( github.head.ref , 'feature-' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo-failure
        run: |
          echo "This is not an allowed branch $GITHUB_HEAD_REF"
          exit 1
